### ISSUE TITLE
[minor] - clicking on search icon without filling in search

### ISSUE THREAD

**Issue by chencal-1622780** [Boneato/bonito#27] opened 2019-12-09 14:29 UTC
**Describe the bug**
There seems to be two types of results page when there is no results found. One results will display " 0. results founds" and the other result page will display nothing after you click the search icon. 

**To Reproduce**
1. Go to website
2. Type in random jargon and click submit
3. Look at the results page
4. Go back to home button
5. Click on search icon without typing anything
6. Look at results page again

**Expected behavior**
Results page displaying nothing should result in only displaying one result page

**Screenshots**
<img width="1430" alt="Screen Shot 2019-12-09 at 6 25 55 AM" src="https://user-images.githubusercontent.com/26780640/70443574-3d366380-1a4d-11ea-8fd3-fded8c9f0011.png">
<img width="1429" alt="Screen Shot 2019-12-09 at 6 26 15 AM" src="https://user-images.githubusercontent.com/26780640/70443576-3e679080-1a4d-11ea-976c-348d5f5a8888.png">

**Additional context**

**Comment by anthonyqcn** [comment] 2019-12-10 06:02
There's two different results displayed when there's two different inputs, hence the difference in results pages. However, the second screenshot is a valid bug but is a duplicate of [issue 16](https://github.com/Boneato/bonito/issues/16)

**Closed as completed by anthonyqcn** 2019-12-10 06:02 UTC
Labels: duplicate, minor
