### ISSUE TITLE
[minor] Searching with no input values return blank page

### ISSUE THREAD

**Issue by LeoKwo** [Boneato/bonito#22] opened 2019-12-07 23:59 UTC
**Describe the bug**
Press search without entering anything would lead to a blank page

**To Reproduce**
1. Login status won't affect the outcome of this bug.
2. On the homepage, click on the search icon
3. Will be redirected to a blank page.

**Expected behavior**
Expected some feedback that an empty search is not allowed. Or that an empty search does not return any result.

**Screenshots**
![Screen Shot 2019-12-07 at 15 57 58](https://user-images.githubusercontent.com/37886365/70382045-597db780-190a-11ea-8bef-08f09593ce7a.jpg)
![Screen Shot 2019-12-07 at 15 58 10](https://user-images.githubusercontent.com/37886365/70382047-5f739880-190a-11ea-81e6-037f4fd8aa8c.jpg)

**System**
- OS: macOS 10.15.1
- Browser: Chrome
- Version: 78.0.3904.108

**Comment by anthonyqcn** [comment] 2019-12-09 09:09
Duplicate of [issue 9](https://github.com/Boneato/bonito/issues/9)

**Closed as completed by anthonyqcn** 2019-12-09 09:09 UTC
Labels: duplicate, minor
