### ISSUE TITLE
[minor] Incorrect cursor for About page images

### ISSUE THREAD

**Issue by aionescu219** [Boneato/bonito#30] opened 2019-12-09 22:45 UTC
**Describe the bug**
On about page, hovering over images, cursor becomes finger pointer but icons are not clickable. This is confusing for the user and potentially irritating. But I like your app :)

**To Reproduce**
1. Go to About
2. Hover over images.
3. Attempt to click - nothing happens

**Expected behavior**
Either the icons should be clickable to give some result or the cursor should remain an arrow.

**Screenshots**

**Additional context**
Using HP Spectre x60x running Windows 10
Firefox browser

**Comment by anthonyqcn** [comment] 2019-12-10 05:58
Duplicate of [issue 15](https://github.com/Boneato/bonito/issues/15)

**Closed as completed by anthonyqcn** 2019-12-10 05:58 UTC
Labels: duplicate
