### ISSUE TITLE
[minor]Cannot start a new search on the search result page

### ISSUE THREAD

**Issue by GarsonYang** [Boneato/bonito#24] opened 2019-12-09 00:52 UTC
**Describe the bug**
Users cannot start a new search on the search result page.

**To Reproduce**
1. Go to the website
2. Input some search words and click on "search"
3. Trying to start a new search on the page without clicking on the button at the top right corner but failed.

**Expected behavior and rationale**
I expect to do another search right away on the same page. Users may not want keep going back the home page for a new search.

**Comment by anthonyqcn** [comment] 2019-12-09 09:09
Duplicate of [issue 12](https://github.com/Boneato/bonito/issues/12)

**Closed as completed by anthonyqcn** 2019-12-09 09:09 UTC
Labels: duplicate, minor
